# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db88ad1bb1afbe9e4dd49a39cb2ba222c847ef9292ac1b7e6dd4b0976e37e3ee22c45bf593b8d8dd6950d9c0be512bf3ba00f71f98cdf9f4750a3c7d15db42e1

test:
  secret_key_base: aa289b88e173cc87a6ae23d41ae851fef1668f28b7a4e04bf8d7e61b31f301f62cc2b096159553005103293548febd895a31697a7567a0d9b78e56ce24aae339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
